# Generated by Django 5.0.1 on 2024-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('in_which_class', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_phone_number', models.CharField(max_length=15)),
                ('mother_phone_number', models.CharField(max_length=15)),
                ('personal_phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
